### ISSUE TITLE
Repeat for non-protected applications

### ISSUE THREAD

**Issue by chrysn** [core-wg/echo-request-tag#1]
I'd consider toning down the "Repeat option MUST be integrity
protected" part. Off my head, amplification mitigation against fake
source addresses comes to my mind. (Eg. a public RD might, when a new
client first ask for a 1024+ byte message with a ~20 byte one, send
Repeat to make sure it does not participate in NTP-style DDOS).

**Comment by gselander** [comment]
Agreed, make it SHOULD and a security consideration.

**Comment by chrysn** [comment]
I've made a change to reflect that in 7aca7f47. It's a little different, but I think it's more to the point:

* It keeps the MUST but limits it to when Repeat is used to serve freshness
* The DDOS mitigation is now phrased as a feature that refrences a security consideration of RFC7252 (it's not really a security issue with the request tag -- it's a security issue already existing and described there (and possibly in https://github.com/core-wg/oscoap/issues/138), Repeat just provides mitigation).

@gselander, if that's fine with you please close the issue.

**Comment by gselander** [comment]
This is fine. Just one detail: In the application no. 4 you added in 7aca7f4 , the statement
"For this application, the Repeat option is used in messages that are not integrity protected."
appear as applying to all applications. I changed that in e3e9474 . No further actions are needed.
