### ISSUE TITLE
Better name for Repeat option

### ISSUE THREAD

**Issue by chrysn** [core-wg/echo-request-tag#13]
The Repeat option obviously needs renaming from the feedback we've gathered, but nobody suggested any better name.

Candidates I'm collecting:
* Challenge (quite generic term)
* Echo (sticking with the current mental image but using a less laden term)
* Cookie (in analogy to the DTLS handshake's Cookie, but people might not like the taste of dough and chocolate)
* Freshness (indicates its purpose but not its mechanism, could be confused with a time value)
* maybe a compositum of those, like Freshness-Challenge?

My personal favorite right now is Freshness-Challenge; @gselander, should we ask back about this on-list again, or just take another shot?

**Comment by chrysn** [comment]
More candidates that have come up:

* Fresh (see Freshness)
* Nonce (IMO too easy to mix up with OSCOAP's partial IV)
* Reiterate (I'd put that in a category with Echo)
* Copy
* Roger

My current personal favorite is Echo.

**Comment by gselander** [comment]
Fixed in ee28aee
