### ISSUE TITLE
Request-Tag: Check NoCacheKey

### ISSUE THREAD

**Issue by chrysn** [core-wg/echo-request-tag#2]
As far as I understand, NoCacheKey becomes irrelevant if an option is both critical and unsafe (because it has to be *understood* by all parties anyway); nevertheless, it remains to decide whether the option should be part of the Cache Key, because that's part of the option number, and implementations will be glad if they can use the behavior implied by number.

**Comment by gselander** [comment]
Does this refer to Repeat or Request-Tag?

Repeat, of course, is not useful for other requests, but may anyway potentially have a cache key to avoid cache hits in legacy proxies (like Object-Security).

Request-Tag probably should probably have the same properties as Block1.

**Comment by chrysn** [comment]
I opened the issue for Request-Tag, and yes, picking the option set of Block1 is a good idea.

I hadn't thought about the options of Repeat before -- but thinking of it now, I think that Repeat option could well be NoCacheKey, because a cacheable response can be stored in a proxy and valid even if it was queried without one; but then, "4.03 Repeat this" responses would always need a Max-Age of 0.

**Comment by chrysn** [comment]
Thinking it through, the Request-Tag option can't be forwarded in any fashion anyway, so whether it has the bit pattern of NoCacheKey is truly irrelevant. (Unlike Block1, which may be passed through with some consideration).

The properties of Request-Tag are already as those of Block1 are, and the properties of Repeat seem fine too.
