### ISSUE TITLE
Editorial

### ISSUE THREAD

**Issue by emanjon** [core-wg/echo-request-tag#44]
"Block-Wise" vs. "block-wise" vs. "blockwise"

"Token" vs. "Token"
I think it should be Token.

"freshness tokens"
I think we should rewrite "freshness tokens" to that the word "token" is only used for the CoAP Token.

**Comment by chrysn** [comment]
The Token and block-wise have been addressed in your f9abfe02595c19a6f5d37f88a29cfafa59a3254a.

Any candidates for "freshness tokens" replacement? "freshness indicators" maybe?
