### ISSUE TITLE
Characterization of Request-Tag

### ISSUE THREAD

**Issue by gselander** [core-wg/echo-request-tag#5]
Reading this part many times: 
"It enables the receiving CoAP server to reliably assemble request payloads (blocks) to their message bodies when the individual payloads are integrity protected, and it enables the sending CoAP server to process simultaneous operations on a single resource if the server supports it."
- some questions appear:

-is "reliable" only a characterization of the first part?
-is integrity protection only relevant to the first part?
- Should it be "sending CoAP server"?

Is the following text a potential replacement?

"It enables the receiving CoAP server supporting this option to reliably assemble request payloads (blocks) to their message bodies, and reliably process simultaneous blockwise request operations on a single resource. The requests MUST to be be integrity protected in order to protect against interchange of blocks between different message bodies."

**Comment by chrysn** [comment]
I moved the server "supporting this option" because body protection actually even works for servers that don't support it, and lowercased the MUST (because it's introductory description and not the specifying part)
