### ISSUE TITLE
updates [RFC7252] with a recommendation that servers use the Echo option

### ISSUE THREAD

**Issue by emanjon** [core-wg/echo-request-tag#70]
This is only mentioned in Abstract and intro. I think it need there needs to be some text in the body as well. The other Update has it's own subsection. "4.2.  Updated Token Processing Requirements for Clients"

**Comment by gselander** [comment]
I added text on server requirements in #71

**Comment by chrysn** [comment]
updated with one more commit:

    Shorten amplification-mitigateion-recommendation paragraph, align text
    
    * The "RECOMMENDED" wording is removed from the description of the
      mechanism (it was under-explained there, the new section does it
      right, and there's no need to make readers wonder about updating at
      this point)
    
    * Reference updated simplified (we're already talking about server side
      in the paragraph)
    
    * Comment about moving text here removed, and replaced with a more
      precise reference
    
      I've toyed with moved text, but it rips the use cases up to the point
      where we'd have to re-do all the items as subsections for
      consistency.

... and merging (comments still appreciated, but I need the branches consolidated for futher editing)

**Comment by chrysn** [comment]
(... and that comment should have gone to #70 ... anyway)

**Comment by gselander** [comment]
Some reformulations in febc426. I think this is ready to close.

**Comment by chrysn** [comment]
Has long been ready, and recently gotten a more explicit cross-reference too.
