### ISSUE TITLE
The Echo Spectrum

### ISSUE THREAD

**Issue by chrysn** [core-wg/echo-request-tag#74]
This is primarily a heads-up for how I intend to address Ben's comments that start with

> Thank you for working on this document; these mechanisms are important
> and will help fill some long-standing gaps in CoAP operation.  That
> said, I do have some fairly substantive comments that might result in
> significant text changes.
> 
> While I recognize that there is going to be a spectrum of requirements
> for determining freshness, I would have expected the far extreme of that
> spectrum to include a strongly time-limited single-use cryptographic
> nonce (akin to what the ACME protocol of RFC 8555 uses but with time
> limit), as well as discussion of some points on the spectrum and which
> ones might be more or less appropriate in various cases.  I do see some
> discussion of different use cases, but not much about the tradeoffs
> along the spectrum, and no discussion at all about the strongest
> properties that it is possible to obtain with this mechanism.

(and the topic comes up again both in his individual points and other reviewers').

---

Plan is (and text is WIP) to have a Characterization of Echo Applications subsection after the applications 1-4 that's started with

> Use cases for the Echo option 
can be characterized by several criteria that help determine the required properties of the Echo value.
These criteria apply both to those listed in {{echo-app}} and any novel applications.
They provide rationale for the statements in the former, and guidance for the latter.

and contains sub-items on what is the synchronized property, time-vs-event (which may eventually say that events are in a sense a monotonic-but-very-non-uniform time) and something about how good the assurance is that I can't quite put my finger on yet.

The PR should, if I get it right, consist of a subsection addition, followed by some simplifcations / backreferences in other parts of the text where the statements are currently spread.

**Comment by gselander** [comment]
Sounds good to me to have a separate subsection. We may want to rethink the order of subsections of section 2. Examples in current section 2.4 Applications ... may fit better at the very end, once the structure of different freshness requirements are laid out. Perhaps consider to write the subsection somewhat self-contained without too much thinking of current order of things (if it makes sense).
