### ISSUE TITLE
OSCOAP outer blockwise option, block1.

### ISSUE THREAD

**Issue by T0bbe** [core-wg/echo-request-tag#9]
Firstly, I am unsure if I should file this issue here or in the OSCOAP repo. 

What error message should the server send to the client if the client is missing the Request Tag when Block1 is set. (In the case of OSCOAP, with outer block options the Request Tag MUST be used. Thus  #3 cannot be applied to the OSCOAP case). 

So which error message, to indicate to the client that it must use Request Tag?

Best regards,
Tobias

**Comment by chrysn** [comment]
The server does not need to check whether the tag is missing, and in some situations can't know. (For example, if the client decided to abandon an earlier blockwise request, it can continue with a Block1=0 for another request at the same resource and, if no messages were lost, use the absent Request-Tag option just fine.)

The server only checks to see if the to-be-processed blocks have matching tags, and either discards old blocks (as in the example above) or just sends 4.08 Request Entity Incomplete if a Block1!=0 exchange arrives that the server wants to process atomically but can't for lack of a Block1=0 exchange that has arrived with a compatible Request-Tag value.

I'm leaving this open as I want to make this more obvious from the document's text.
